# Static Traefik configuration

defaultEntryPoints:
  - http
  - https

log:
  level: debug

api:
  dashboard: true

entryPoints:
  http:
    address: ':80'
  https:
    address: ':443'

serversTransport:
  # Only with dev env to skip tls verification
  insecureSkipVerify: true

providers:
  docker:
    swarmMode: false
    watch: true
    exposedbydefault: false
  file:
    watch: true
    directory: /etc/traefik/
    filename: dynaefik.yml
