version: "3"
services:

  traefik:
    image: efc_traefik:2.0.5
    ports:
      - "80:80"
      - "443:443"
    labels:
      # Traefik activation
      - "traefik.enable=true"
      # Traefik service declaration
      - "traefik.http.services.api@internal.loadbalancer.server.port=8080"
      # Traefik insecure router declaration
      - "traefik.http.routers.traefik_insecure.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.traefik_insecure.service=api@internal"
      - "traefik.http.routers.traefik_insecure.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik_insecure.entrypoints=http"
      - "traefik.http.routers.traefik_insecure.middlewares=base_redirect_http_to_https@file"
      # Traefik secure router declaration
      - "traefik.http.routers.traefik_secure.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.traefik_secure.service=api@internal"
      - "traefik.http.routers.traefik_secure.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik_secure.tls=true"
      - "traefik.http.routers.traefik_secure.entrypoints=https"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  default:
    external:
        name: ols_dev